# Generated by Django 3.0.5 on 2020-06-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200616_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='statys',
            new_name='status',
        ),
    ]
